import {
  Book,
  Bookmark,
  BriefcaseBusiness,
  ChevronDownIcon,
  ChevronUp,
  CirclePlay,
  CircleUserRound,
  Edit,
  Facebook,
  Fingerprint,
  FolderOpenDot,
  House,
  Instagram,
  LayoutDashboard,
  Linkedin,
  LogOut,
  Menu,
  MessageCircle,
  MessageCircleMore,
  MoveRight,
  Phone,
  Plus,
  Search,
  Shield,
  Star,
  Twitter,
  User,
  Users,
  X,
  Youtube,
} from "lucide-react";

export const ICONS = {
  BARS: Menu,
  CLOSE: X,
  ARROW_DOWN: ChevronDownIcon,
  ARROW_UP: ChevronUp,
  MOVE_RIGHT: MoveRight,
  PHONE: Phone,
  FINGERPRINT: Fingerprint,
  CIRCLE_PLAY: CirclePlay,
  SEARCH: Search,
  STAR: Star,
  SHIELD: Shield,
  USERS: Users,
  BRIEFCASE: BriefcaseBusiness,
  BOOK: Book,
  MESSAGECIRCLE: MessageCircleMore,
  DASHBOARD: LayoutDashboard,
  PROFILE: CircleUserRound,
  HOME: House,
  SIGNOUT: LogOut,
  EDIT: Edit,
  BOOKMARK: Bookmark,
  PLUS: Plus,
  FOLDER: FolderOpenDot,

  //Social Icons
  FACEBOOK: Facebook,
  LINKEDIN: Linkedin,
  TWITTER: Twitter,
  INSTAGRAM: Instagram,
  YOUTUBE: Youtube,
};
